# Generated by Django 5.2.6 on 2025-10-09 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_comment_parent_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
