# Generated by Django 5.2.6 on 2025-10-28 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_alter_album_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
