# Generated by Django 5.2.6 on 2025-11-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0013_albumreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='report',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.album'),
        ),
        migrations.AlterField(
            model_name='report',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
        ),
        migrations.DeleteModel(
            name='AlbumReport',
        ),
    ]
