# Generated by Django 5.2.6 on 2025-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_remove_report_reviewed_report_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
    ]
